package com.koma.weather.data.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.koma.weather.data.model.AqiInfo.CityInfo;
import com.koma.weather.util.CityInfoConverter;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "aqi_info".
*/
public class AqiInfoDao extends AbstractDao<AqiInfo, Long> {

    public static final String TABLENAME = "aqi_info";

    /**
     * Properties of entity AqiInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CityInfo = new Property(1, String.class, "cityInfo", false, "CITY_INFO");
    }

    private final CityInfoConverter cityInfoConverter = new CityInfoConverter();

    public AqiInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AqiInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"aqi_info\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CITY_INFO\" TEXT);"); // 1: cityInfo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"aqi_info\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AqiInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        CityInfo cityInfo = entity.getCityInfo();
        if (cityInfo != null) {
            stmt.bindString(2, cityInfoConverter.convertToDatabaseValue(cityInfo));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AqiInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        CityInfo cityInfo = entity.getCityInfo();
        if (cityInfo != null) {
            stmt.bindString(2, cityInfoConverter.convertToDatabaseValue(cityInfo));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AqiInfo readEntity(Cursor cursor, int offset) {
        AqiInfo entity = new AqiInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cityInfoConverter.convertToEntityProperty(cursor.getString(offset + 1)) // cityInfo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AqiInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCityInfo(cursor.isNull(offset + 1) ? null : cityInfoConverter.convertToEntityProperty(cursor.getString(offset + 1)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AqiInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AqiInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AqiInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
