package com.koma.weather.data.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.koma.weather.data.model.WeatherModel;

import com.koma.weather.data.model.WeatherModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weatherModelDaoConfig;

    private final WeatherModelDao weatherModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weatherModelDaoConfig = daoConfigMap.get(WeatherModelDao.class).clone();
        weatherModelDaoConfig.initIdentityScope(type);

        weatherModelDao = new WeatherModelDao(weatherModelDaoConfig, this);

        registerDao(WeatherModel.class, weatherModelDao);
    }
    
    public void clear() {
        weatherModelDaoConfig.clearIdentityScope();
    }

    public WeatherModelDao getWeatherModelDao() {
        return weatherModelDao;
    }

}
